parameters:
  stripe.secret_key: "%env(STRIPE_SECRET_KEY)%"
  stripe.webhook_secret: "%env(STRIPE_WEBHOOK_SECRET)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\Back\PaymentController:
    arguments:
      $stripeSecretKey: '%stripe.secret_key%'
      $stripeWebhookSecret: '%stripe.webhook_secret%'

  App\Service\StripeService:
    arguments:
      $stripeApiKey: '%stripe.secret_key%'

  App\Service\QuoteService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  Dompdf\Dompdf:
      arguments:
          $options: '@Dompdf\Options'
  Dompdf\Options:
      calls:
          - method: set
            arguments:
                - 'defaultFont'
                - 'Arial'

  App\Form\UserType:
      arguments:
          $security: '@security.helper'

  App\Twig\AccessExtension:
      tags:
          - { name: twig.extension }

  App\Controller\Back\ReportController:
    arguments:
      $reportGenerationService: '@App\Service\ReportGenerationService'
      $pdfExportService: '@App\Service\PDFExportService'
      $reportRepository: '@App\Repository\ReportRepository'
      $userService: '@App\Service\UserService'
      $security: '@security.helper'

  App\Service\UserService:
    arguments:
      $security: '@security.helper'

  App\Twig\JsonDecodeExtension:
    tags:
      - { name: twig.extension }
