parameters:
  stripe.secret_key: "%env(STRIPE_SECRET_KEY)%"
  stripe.webhook_secret: "%env(STRIPE_WEBHOOK_SECRET)%"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  App\Controller\Back\PaymentController:
    arguments:
      $stripeSecretKey: '%stripe.secret_key%'
      $stripeWebhookSecret: '%stripe.webhook_secret%'

  App\Service\StripeService:
    arguments:
      $stripeApiKey: '%stripe.secret_key%'

  App\Service\QuoteService:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
